controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_controller:
      type: mecanum_drive_controller/MecanumDriveController

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    prismatic_controller:
      type: joint_trajectory_controller/JointTrajectoryController

mecanum_controller:
  ros__parameters:
    front_left_wheel_command_joint_name: "Front_left_wheel_Joint"
    front_right_wheel_command_joint_name: "Front_right_wheel_Joint"
    rear_left_wheel_command_joint_name: "Rear_left_wheel_Joint"
    rear_right_wheel_command_joint_name: "Rear_right_wheel_Joint"

    kinematics:
      wheels_radius: 0.05
      sum_of_robot_center_projection_on_X_Y_axis: 0.157

    reference_timeout: 2.0 
    
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    enable_odom_tf: true
    use_stamped_vel: false
    use_sim_time: true
arm_controller:
  ros__parameters:
    joints:
      - Arm_Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    use_sim_time: true

prismatic_controller:
  ros__parameters:
    joints:
      - Prismatic_Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    use_sim_time: true
